version: "3.7"
services:
    nextjs_dev:
        build:
            context: .
            dockerfile: Dockerfile-dev5
        ports:
            - "5002:5002"
        volumes:
            - ".:/app"
            - "/app/node_modules"
        links:
            - redis
        environment:
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
            WALLET: "/app/oracle/wallet"            
            API_ENDPOINT: "https://api.vocabsitory.site/api"
        image: nextjs_dev
        container_name: nextjs_dev
        
    redis:
        restart: always
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]