version: "3.7"
services:
    nextjs_dev:
        build:
            context: .
            dockerfile: Dockerfile-dev
        ports:
            - "5002:5002"
        volumes:
            - ".:/app"
            - "/app/node_modules"
        #links:
        #    - redis
        environment:
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
            WALLET: "/app/oracle/wallet"            
            API_ENDPOINT: "https://api.vocab.services/api"
            #"http://150.230.38.246:3000"
            #"https://api.vocabsitory.site/api"
        image: nextjs_dev
        container_name: nextjs_dev
networks:
    default:
        name: "composite_network"
        external: true